sonar.projectKey=AramisN_aws-databricks-lakehouse
sonar.organization=aramisn

sonar.sources=generator
sonar.tests=generator/tests
sonar.exclusions=**/tests/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
